/// Flutter icons Meeting
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Meeting
///      fonts:
///       - asset: fonts/Meeting.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Meeting {
  Meeting._();

  static const _kFontFam = 'Meeting';
  static const String? _kFontPkg = null;

  static const IconData accountgroup =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
